flags: {}
packages:
- .
extra-deps:
- ViennaRNAParser-1.3.1
- aeson-0.11.3.0
- bytestring-builder-0.10.6.0.0
- directory-1.2.7.1
- hjsmin-0.1.5.4
- http-api-data-0.2.4
- http-client-0.4.31.2
- http-client-tls-0.2.4.1
- http-conduit-2.1.11
- http2-1.3.1
- language-javascript-0.5.14.7
- optparse-applicative-0.13.0.0
- persistent-2.2.4.1
- persistent-sqlite-2.2.1.1
- persistent-template-2.1.8.1
- wai-3.0.5.0
- wai-logger-2.2.7
- warp-3.1.12
- yesod-test-1.4.4
- yesod-form-1.4.10
compiler-check: newer-minor
resolver: lts-8.16
