flags: {}
packages:
- '.'
extra-deps:
- aeson-0.9.0.1
- hjsmin-0.1.5.4
- http2-1.3.1
- language-javascript-0.5.14.7
- optparse-applicative-0.13.0.0
- wai-3.0.5.0
- warp-3.1.12
- yesod-test-1.4.4
compiler-check: newer-minor
resolver: lts-6.22
